# Workflow name
name: CI
# Events # 指定在main分支发生pull_request事件时才触发运行工作流程
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  # Jobs name
  Test:
    runs-on: ubuntu-latest
    steps:
      # steps name # 拉取项目代码
      - name: Checkout repository
        # Actions name
        uses: actions/checkout@v3
      # 下载node
      - name: Use Node.js
        # Actions name
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      # 安装依赖
      - name: Installing Dependencies
        run: npm install --legacy-peer-deps
      # 运行代码扫描
      - name: Running Lint
        run: npm run lint
      # 运行自动化测试
      - name: Running Test
        run: npm run test:unit
